### ISSUE TITLE
  install FILES given no DESTINATION!

### ISSUE THREAD

**Issue by bookdude** [pothosware/SoapySDR#132] opened 2017-07-27 13:51 UTC
Fails when installing as part of gr-gsm pybomb.

Installs without issue stand alone via clone \ cmake on the same system.

root@pi-gsm-01:~/git/SoapySDR/build# pybombs install gr-gsm
PyBOMBS - INFO - PyBOMBS Version 2.3.1
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
Install tree:
|
\- gr-gsm
   |
   \- gr-osmosdr
      |
      +- airspy
      |
      +- hackrf
      |
      \- soapysdr
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: soapysdr
PyBOMBS.Packager.source - WARNING - Build dir already exists: /usr/local/src/soapysdr/build
Configuring: (100%) [======================================================================================================================================================================================================================]
PyBOMBS.Packager.source - WARNING - Configuration failed. Re-trying with higher verbosity.
-- 
-- #############################################
-- ## Begin configuration for Python support...
-- #############################################
-- Enabling optional Python bindings if possible...
-- SWIG_FOUND: TRUE - 2.0.12
-- PYTHONINTERP_FOUND: TRUE - 2.7.12
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_INSTALL_DIR: ${prefix}/lib/python2.7/dist-packages
-- PYTHONLIBS_FOUND: TRUE - 2.7.12
-- PYTHON_INCLUDE_DIRS: /usr/include/python2.7
-- PYTHON_LIBRARIES: /usr/lib/arm-linux-gnueabihf/libpython2.7.so
-- CMAKE_SWIG_FLAGS=-c++;-threads;-DSIZE_T_IS_UNSIGNED_INT
-- 
-- #############################################
-- ## Begin configuration for Python3 support...
-- #############################################
-- Enabling optional Python3 bindings if possible...
-- SWIG_FOUND: TRUE - 2.0.12
-- Could NOT find Python3InterpDbg (missing:  PYTHON3_DBG_EXECUTABLE) 
-- PYTHON3INTERP_FOUND: TRUE
-- PYTHON3_EXECUTABLE: /usr/bin/python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/distutils/sysconfig.py", line 14, in <module>
    import re
  File "/usr/lib/python3.5/re.py", line 335, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/dist-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/usr/lib/python3.5/re.py", line 335, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/dist-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/distutils/sysconfig.py", line 14, in <module>
    import re
  File "/usr/lib/python3.5/re.py", line 335, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/dist-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
-- PYTHON3_INSTALL_DIR: ${prefix}/
-- PYTHON3LIBS_FOUND: TRUE
-- PYTHON3_INCLUDE_DIRS: /usr/include/python3.5m
-- PYTHON3_LIBRARIES: /usr/lib/arm-linux-gnueabihf/libpython3.5m.so
-- CMAKE_SWIG_FLAGS=-c++;-threads;-DSIZE_T_IS_UNSIGNED_INT
CMake Error at python3/CMakeLists.txt:87 (install):
  install TARGETS given no LIBRARY DESTINATION for module target
  "_SoapySDR3".

CMake Error at python3/CMakeLists.txt:92 (install):
  install FILES given no DESTINATION!

-- 
-- ######################################################
-- ## SoapySDR enabled features
-- ######################################################
-- 
 * Library , runtime library v0.6.1-g8c5db3e2
 * Tests , library unit tests
 * Docs , doxygen documentation
 * Python , python bindings v2.7.12
 * Python3 , python3 bindings

-- ######################################################
-- ## SoapySDR disabled features
-- ######################################################
-- 

-- SoapySDR version: v0.6.1-g8c5db3e2
-- ABI/so version: v0.6
-- Install prefix: /usr/local
-- Configuring incomplete, errors occurred!
See also "/usr/local/src/soapysdr/build/CMakeFiles/CMakeOutput.log".
PyBOMBS.Packager.source - ERROR - Configuration failed after running at least twice.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package soapysdr:
Configuration failed
PyBOMBS.install_manager - ERROR - Error installing package soapysdr. Aborting.
root@pi-gsm-01:~/git/SoapySDR/build#

**Comment by guruofquality** [comment] 2017-07-27 14:11
@bookdude It looks like its dying when trying to call into python to get an install prefix. This is basically the underlying command, so it might be useful to figure out why its bombing on your system, I'm curious if it is also erroring out when run manually.

```
 /usr/bin/python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=True, prefix=''))"
```

anyway, the PYTHON3_INSTALL_DIR is empty because of the error and the configure is broken for that reason. Two work arounds if you cant reproduce and fix the error:

* pass `-DPYTHON3_INSTALL_DIR=desired path` (this should override the automatic one)
* or if not using python3: `-DENABLE_PYTHON3=OFF`

**Comment by robman501a** [comment] 2017-08-10 13:40
This didn't seem to do anything. ' /usr/bin/python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=True, prefix=''))" '
As for this....
rob@ubuntu:~$ python3 -c "import sys; print(sys.path)"
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']

I'm not quite sure on where I should put this.
'pass -DPYTHON3_INSTALL_DIR=desired path (this should override the automatic one)' and what path do I use?
or if not using 'python3: -DENABLE_PYTHON3=OFF'

**Comment by guruofquality** [comment] 2017-08-10 15:44
> This didn't seem to do anything. ' /usr/bin/python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=True, prefix=''))" '

@robman501a Are you able to clone and configure SoapySDR without this error (outside of pybombs, just git clone and mkdir build, cd build && cmake ../) I'm wondering if pybombs overloads the PYTHONPATH environment variable and causes python3 to crash. I don't think python3 is a big use case for pybombs apps, so maybe its ok to disable it in this case. Just a guess, but if cmake fails in pybombs and is ok without it, maybe thats the cause...

> I'm not quite sure on where I should put this.
'pass -DPYTHON3_INSTALL_DIR=desired path (this should override the automatic one)' and what path do I use?
or if not using 'python3: -DENABLE_PYTHON3=OFF'

Its cmake arguments for SoapySDR project, so probably in the relevant pybomb file, I cant advice much more there. but I assume there is a place to add configuration args for cmake projects, since a lot of the pybombs apps are cmake based

**Comment by robman501a** [comment] 2017-08-10 20:29
No issues building SoapySDR outside of PyBombs.

rob@ubuntu:~/SoapySDR/build$ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") 
-- 
-- #############################################
-- ## Begin configuration for Python support...
-- #############################################
-- Enabling optional Python bindings if possible...
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.10") 
-- SWIG_FOUND: TRUE - 3.0.10
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- PYTHONINTERP_FOUND: TRUE - 2.7.13
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_INSTALL_DIR: ${prefix}/lib/python2.7/dist-packages
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.13") 
-- PYTHONLIBS_FOUND: TRUE - 2.7.13
-- PYTHON_INCLUDE_DIRS: /usr/include/python2.7
-- PYTHON_LIBRARIES: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Performing Test SIZE_T_IS_UNSIGNED_INT
-- Performing Test SIZE_T_IS_UNSIGNED_INT - Failed
-- CMAKE_SWIG_FLAGS=-c++;-threads
-- 
-- #############################################
-- ## Begin configuration for Python3 support...
-- #############################################
-- Enabling optional Python3 bindings if possible...
-- SWIG_FOUND: TRUE - 3.0.10
-- Found Python3Interp: /usr/bin/python3  
-- Found Python3InterpDbg: /usr/bin/python3-dbg  
-- PYTHON3INTERP_FOUND: TRUE
-- PYTHON3_EXECUTABLE: /usr/bin/python3
-- PYTHON3_INSTALL_DIR: ${prefix}/lib/python3/dist-packages
-- Found Python3Libs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so  
-- PYTHON3LIBS_FOUND: TRUE
-- PYTHON3_INCLUDE_DIRS: /usr/include/python3.5m
-- PYTHON3_LIBRARIES: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- CMAKE_SWIG_FLAGS=-c++;-threads
-- 
-- ######################################################
-- ## SoapySDR enabled features
-- ######################################################
-- 
 * Library , runtime library v0.6.1-gc772ee1b
 * Tests , library unit tests
 * Docs , doxygen documentation
 * Python , python bindings v2.7.13
 * Python3 , python3 bindings

-- ######################################################
-- ## SoapySDR disabled features
-- ######################################################
-- 

-- SoapySDR version: v0.6.1-gc772ee1b
-- ABI/so version: v0.6
-- Install prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rob/SoapySDR/build
rob@ubuntu:~/SoapySDR/build$ make -j4
Scanning dependencies of target SoapySDR
Scanning dependencies of target docs
[  2%] Generating documentation with doxygen
[  5%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Registry.cpp.o
[  8%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Factory.cpp.o
[ 10%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Device.cpp.o
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Searching for files in directory /home/rob/SoapySDR/include/SoapySDR
Reading and parsing tag files
Parsing files
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Config.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Config.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Config.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Config.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Constants.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Constants.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Device.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Device.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Device.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Device.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Errors.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Errors.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Errors.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Errors.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Formats.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Formats.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Formats.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Formats.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Logger.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Logger.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Logger.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Logger.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Modules.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Modules.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Modules.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Modules.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Registry.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Registry.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Time.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Time.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Time.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Time.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Types.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Types.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Types.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Types.hpp...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Version.h...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Version.h...
Preprocessing /home/rob/SoapySDR/include/SoapySDR/Version.hpp...
Parsing file /home/rob/SoapySDR/include/SoapySDR/Version.hpp...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Creating members for template instances...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating code for file Config.h...
Generating code for file Config.hpp...
Generating code for file Constants.h...
Generating code for file Device.h...
Generating code for file Device.hpp...
Generating code for file Errors.h...
Generating code for file Errors.hpp...
Generating code for file Formats.h...
Generating code for file Formats.hpp...
Generating code for file Logger.h...
Generating code for file Logger.hpp...
Generating code for file Modules.h...
Generating code for file Modules.hpp...
Generating code for file Registry.hpp...
Generating code for file Time.h...
Generating code for file Time.hpp...
Generating code for file Types.h...
Generating code for file Types.hpp...
Generating code for file Version.h...
Generating code for file Version.hpp...
Generating file documentation...
Generating docs for file Config.h...
Generating docs for file Config.hpp...
Generating docs for file Constants.h...
Generating docs for file Device.h...
Generating docs for file Device.hpp...
Generating docs for file Errors.h...
Generating docs for file Errors.hpp...
Generating docs for file Formats.h...
Generating docs for file Formats.hpp...
Generating docs for file Logger.h...
Generating docs for file Logger.hpp...
Generating docs for file Modules.h...
Generating docs for file Modules.hpp...
Generating docs for file Registry.hpp...
Generating docs for file Time.h...
Generating docs for file Time.hpp...
Generating docs for file Types.h...
Generating docs for file Types.hpp...
Generating docs for file Version.h...
Generating docs for file Version.hpp...
Generating page documentation...
Generating docs for page deprecated...
Generating group documentation...
Generating class documentation...
Generating docs for compound SoapySDRArgInfo...
Generating docs for compound SoapySDRKwargs...
Generating docs for compound SoapySDRRange...
Generating namespace index...
Generating docs for namespace SoapySDR
Generating docs for compound SoapySDR::ArgInfo...
Generating docs for compound SoapySDR::Device...
Generating docs for compound SoapySDR::Range...
Generating docs for compound SoapySDR::Registry...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
lookup cache used 582/65536 hits=3117 misses=587
finished...
[ 10%] Built target docs
[ 13%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Types.cpp.o
[ 16%] Building CXX object lib/CMakeFiles/SoapySDR.dir/NullDevice.cpp.o
[ 18%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Logger.cpp.o
[ 21%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Errors.cpp.o
[ 24%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Formats.cpp.o
[ 27%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Modules.cpp.o
[ 29%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Version.cpp.o
[ 32%] Building CXX object lib/CMakeFiles/SoapySDR.dir/TypesC.cpp.o
[ 35%] Building CXX object lib/CMakeFiles/SoapySDR.dir/ModulesC.cpp.o
[ 37%] Building CXX object lib/CMakeFiles/SoapySDR.dir/VersionC.cpp.o
[ 40%] Building CXX object lib/CMakeFiles/SoapySDR.dir/DeviceC.cpp.o
[ 43%] Building CXX object lib/CMakeFiles/SoapySDR.dir/FactoryC.cpp.o
[ 45%] Building CXX object lib/CMakeFiles/SoapySDR.dir/LoggerC.cpp.o
[ 48%] Building CXX object lib/CMakeFiles/SoapySDR.dir/TimeC.cpp.o
[ 51%] Building CXX object lib/CMakeFiles/SoapySDR.dir/ErrorsC.cpp.o
[ 54%] Building CXX object lib/CMakeFiles/SoapySDR.dir/FormatsC.cpp.o
[ 56%] Linking CXX shared library libSoapySDR.so
[ 56%] Built target SoapySDR
Scanning dependencies of target TestFormatParser
Scanning dependencies of target TestKwargsMarkup
Scanning dependencies of target TestTimeConversion
Scanning dependencies of target SoapySDRUtil
[ 59%] Building CXX object tests/CMakeFiles/TestKwargsMarkup.dir/TestKwargsMarkup.cpp.o
[ 62%] Building CXX object tests/CMakeFiles/TestFormatParser.dir/TestFormatParser.cpp.o
[ 64%] Building CXX object tests/CMakeFiles/TestTimeConversion.dir/TestTimeConversion.cpp.o
[ 67%] Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapySDRUtil.cpp.o
[ 70%] Linking CXX executable TestTimeConversion
[ 70%] Built target TestTimeConversion
[ 72%] Swig source
[ 75%] Linking CXX executable TestFormatParser
[ 75%] Built target TestFormatParser
[ 78%] Swig source
[ 81%] Linking CXX executable TestKwargsMarkup
[ 81%] Built target TestKwargsMarkup
[ 83%] Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapySDRProbe.cpp.o
[ 86%] Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapyRateTest.cpp.o
Scanning dependencies of target _SoapySDR
[ 89%] Building CXX object python/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o
Scanning dependencies of target _SoapySDR3
[ 91%] Building CXX object python3/CMakeFiles/_SoapySDR3.dir/SoapySDRPYTHON_wrap.cxx.o
[ 94%] Linking CXX executable SoapySDRUtil
[ 94%] Built target SoapySDRUtil
[ 97%] Linking CXX shared module _SoapySDR.so
[100%] Linking CXX shared module _SoapySDR.so
[100%] Built target _SoapySDR
[100%] Built target _SoapySDR3
rob@ubuntu:~/SoapySDR/build$ sudo make install
[ 54%] Built target SoapySDR
[ 64%] Built target SoapySDRUtil
[ 70%] Built target TestTimeConversion
[ 75%] Built target TestFormatParser
[ 81%] Built target TestKwargsMarkup
[ 83%] Built target docs
[ 91%] Built target _SoapySDR
[100%] Built target _SoapySDR3
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/share/cmake/SoapySDR/SoapySDRConfig.cmake
-- Installing: /usr/local/share/cmake/SoapySDR/SoapySDRUtil.cmake
-- Installing: /usr/local/share/cmake/SoapySDR/SoapySDRConfigVersion.cmake
-- Installing: /usr/local/include/SoapySDR
-- Installing: /usr/local/include/SoapySDR/Logger.hpp
-- Installing: /usr/local/include/SoapySDR/Constants.h
-- Installing: /usr/local/include/SoapySDR/Registry.hpp
-- Installing: /usr/local/include/SoapySDR/Modules.hpp
-- Installing: /usr/local/include/SoapySDR/Modules.h
-- Installing: /usr/local/include/SoapySDR/Errors.h
-- Installing: /usr/local/include/SoapySDR/Errors.hpp
-- Installing: /usr/local/include/SoapySDR/Version.hpp
-- Installing: /usr/local/include/SoapySDR/Time.h
-- Installing: /usr/local/include/SoapySDR/Version.h
-- Installing: /usr/local/include/SoapySDR/Logger.h
-- Installing: /usr/local/include/SoapySDR/Formats.h
-- Installing: /usr/local/include/SoapySDR/Config.h
-- Installing: /usr/local/include/SoapySDR/Device.h
-- Installing: /usr/local/include/SoapySDR/Time.hpp
-- Installing: /usr/local/include/SoapySDR/Formats.hpp
-- Installing: /usr/local/include/SoapySDR/Types.hpp
-- Installing: /usr/local/include/SoapySDR/Device.hpp
-- Installing: /usr/local/include/SoapySDR/Types.h
-- Installing: /usr/local/include/SoapySDR/Config.hpp
-- Installing: /usr/local/lib/libSoapySDR.so.0.6.1
-- Installing: /usr/local/lib/libSoapySDR.so.0.6
-- Installing: /usr/local/lib/libSoapySDR.so
-- Installing: /usr/local/lib/pkgconfig/SoapySDR.pc
-- Installing: /usr/local/bin/SoapySDRUtil
-- Set runtime path of "/usr/local/bin/SoapySDRUtil" to ""
-- Installing: /usr/local/share/man/man1/SoapySDRUtil.1
-- Installing: /usr/local/lib/python2.7/dist-packages/_SoapySDR.so
-- Set runtime path of "/usr/local/lib/python2.7/dist-packages/_SoapySDR.so" to ""
-- Installing: /usr/local/lib/python2.7/dist-packages/SoapySDR.py
-- Installing: /usr/local/lib/python3/dist-packages/_SoapySDR.so
-- Set runtime path of "/usr/local/lib/python3/dist-packages/_SoapySDR.so" to ""
-- Installing: /usr/local/lib/python3/dist-packages/SoapySDR.py
rob@ubuntu:~/SoapySDR/build$ sudo ldconfig #needed on debian systems
rob@ubuntu:~/SoapySDR/build$ SoapySDRUtil --info
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Lib Version: v0.6.1-gc772ee1b
API Version: v0.6.0
ABI Version: v0.6
Install root: /usr/local
Search path: /usr/local/lib/SoapySDR/modules0.6
No modules found!
Loading modules... done
Available factories...null,

**Comment by guruofquality** [comment] 2017-08-10 20:42
That probably means that pybombs is stomping on the PYTHONPATH. Im sure that pybombs is just setting the PYTHONPATH strategically to help it find gnuradio based python libs, and they just do not have to deal with python3 at all. In terms of being a package manager like homebrew, its probably not the best way to go. I'm genuinely curious what the PYTHONPATH is set to, if at all since it seems to be overriding system python packages, not just stuff in /usr/local. Still speculation, none of this is confirmed FWIW.

So anyway, I can think of two things to resolve this:

* Find the maintainer of the soapysdr pybomb and ask them to add `-DENABLE_PYTHON3=OFF` to the cmake arguments. This is probably the easiest and and most straightforward.

* Confirm with pybombs maintainer that it does indeed overwrite the PYTHONPATH, and maybe ask if there is a hook to disable that for certain package configurations or change it to not specify default system install pythons for python

**Comment by robman501a** [comment] 2017-08-10 21:17
Is there a way that I can still use pybombs install gr-gsm and just make it skip the SoapySDR part?

**Comment by robman501a** [comment] 2017-08-10 22:14
'Find the maintainer of the soapysdr pybomb' I have no idea where to look or what to look form.
Would it be a .py file?

**Comment by guruofquality** [comment] 2017-08-10 22:35
I added an issue here: https://github.com/gnuradio/gr-recipes/issues/91

**Comment by robman501a** [comment] 2017-08-11 14:04
Thanks. I wonder how the OP @bookdude is making out with this issue also.

**Comment by guruofquality** [comment] 2017-08-15 00:06
@oe3cts looks like this was your pybombs recipe file, any advice?

**Comment by guruofquality** [comment] 2017-10-05 01:33
Anyway, there is nothing I can do here, its a straightforward build issue. I opened bugs on the correct projects, reported the issue, made a suggestion to either fix the path or to modify the enable flags. Closing. thanks for reporting!

**Closed by guruofquality** 2017-10-05 01:33 UTC
